export const CHANGE_PAGE = "CHANGE_PAGE";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const GET_ACCOUNT_CHANNELS = "GET_ACCOUNT_CHANNELS";
export const GET_INTEGRATIONS = "GET_INTEGRATIONS";
export const GET_VIDEOS = "GET_VIDEOS";
export const GET_SETTINGS = "GET_SETTINGS";